#include <iostream>
#include "LongInt.h"
#include "LongDouble.h"

int main() {
  std::cout << "====== Init LongInt ======" << std::endl;
  LongInt def1;
  std::cout << "Default: " << def1.str() << std::endl;
  LongInt int1(123), int2(-12);
  std::cout << "Int: " << int1.str() << " " << int2.str() << std::endl;
  LongInt str1("134567890987654345678901238781927873821"), str2("-1123902839218398219839283928193892183");
  std::cout << "Str: " << str1.str() << " " << str2.str() << std::endl;
  std::cout << "====== Init LongDouble ======" << std::endl;
  LongDouble def2;
  std::cout << "Default: " << def2.str() << std::endl;
  LongDouble dbl1(10.0), dbl2(13.3), dbl3(-1.0), dbl4(-3.9);
  std::cout << "Double: " << dbl1.str() << " " << dbl2.str() << " " << dbl3.str() << " " << dbl4.str() << std::endl;
  LongInt li1("10000000000");
  LongDouble li2(li1);
  std::cout << "LongInt: " << li2.str() << std::endl;
  LongInt ch1("1"), ch2("-7"), z1("2"), z2("3");
  LongDouble dr1(ch1, z1), dr2(ch2, z2);
  std::cout << "Fraction: " << dr1.str() << " " << dr2.str() << std::endl;
  LongDouble str3("1.3"), str4("0.5"), str5("10000000000000000.000100010001000100010001");
  std::cout << "Str: " << str3.str() << " " << str4.str() << " " << str5.str() << std::endl;
  std::cout << "====== Arithmetic LongInt ======" << std::endl;
  LongInt a("100000000000000000"), b("-1234567890987654");
  std::cout << a.str() << " + " << b.str() << " = " << (a + b).str() << std::endl;
  std::cout << a.str() << " - " << b.str() << " = " << (a - b).str() << std::endl;
  std::cout << a.str() << " * " << b.str() << " = " << (a * b).str() << std::endl;
  std::cout << a.str() << " / " << b.str() << " = " << (a / b).str() << std::endl;
  std::cout << a.str() << " % " << b.str() << " = " << (a % b).str() << std::endl;
  std::cout << "-" << a.str() << " = " << (-a).str() << std::endl;
  std::cout << "|" << a.str() << "| = " << LongInt::abs(a).str() << std::endl;
  std::cout << "|" << b.str() << "| = " << LongInt::abs(b).str() << std::endl << std::endl;
  std::cout << "a = " << a.str() << std::endl;
  std::cout << "b = " << b.str() << std::endl;
  a += b;
  std::cout << "(a+=b): a = " << a.str() << std::endl;
  a *= b;
  std::cout << "(a*=b): a = " << a.str() << std::endl;
  a -= b;
  std::cout << "(a-=b): a = " << a.str() << std::endl;
  a /= b;
  std::cout << "(a/=b): a = " << a.str() << std::endl;
  std::cout << "a * 10 = " << (a * 10).str() << std::endl;
  std::cout << "a * 10.1 = " << ((LongDouble)a * 10.1).str() << std::endl << std::endl;
  a = (LongInt)"98765432109012345";
  std::cout << "a++ = " << (a++).str() << " (a = " << a.str() << ")" << std::endl;
  std::cout << "++a = " << (++a).str() << " (a = " << a.str() << ")" << std::endl;
  std::cout << "a-- = " << (a--).str() << " (a = " << a.str() << ")" << std::endl;
  std::cout << "--a = " << (--a).str() << " (a = " << a.str() << ")" << std::endl;
  std::cout << "====== Arithmetic LongDouble ======" << std::endl;
  LongDouble c("123.13"), d("1.5");std::cout << c.str() << " + " << d.str() << " = " << (c + d).str() << std::endl;
  std::cout << c.str() << " - " << d.str() << " = " << (c - d).str() << std::endl;
  std::cout << c.str() << " * " << d.str() << " = " << (c * d).str() << std::endl;
  std::cout << c.str() << " / " << d.str() << " = " << (c / d).str() << std::endl;
  std::cout << c.str() << " % " << d.str() << " = " << (c % d).str() << std::endl;
  std::cout << "-" << c.str() << " = " << (-c).str() << std::endl;
  std::cout << "|" << c.str() << "| = " << LongDouble::abs(c).str() << std::endl;
  std::cout << "|" << d.str() << "| = " << LongDouble::abs(d).str() << std::endl << std::endl;
  std::cout << "c = " << c.str() << std::endl;
  std::cout << "d = " << d.str() << std::endl;
  c += d;
  std::cout << "(c+=d): c = " << c.str() << std::endl;
  c *= d;
  std::cout << "(c*=d): c = " << c.str() << std::endl;
  c -= d;
  std::cout << "(c-=d): c = " << c.str() << std::endl;
  c /= d;
  std::cout << "(c/=d): c = " << c.str() << std::endl;
  std::cout << "c + 10.1 = " << (c + 10.1).str() << std::endl;
  std::cout << "10 - c = " << (10 - c).str() << std::endl;
  std::cout << "c + 100 = " << (c + 100).str() << std::endl << std::endl;
  c = (LongDouble)"123.63";
  std::cout << "c++ = " << (c++).str() << " (c = " << c.str() << ")" << std::endl;
  std::cout << "++c = " << (++c).str() << " (c = " << c.str() << ")" << std::endl;
  std::cout << "c-- = " << (c--).str() << " (c = " << c.str() << ")" << std::endl;
  std::cout << "--c = " << (--c).str() << " (c = " << c.str() << ")" << std::endl;
  std::cout << "====== Compare ======" << std::endl;
  a = 123;
  c = 150.5;
  std::cout << a.str() << " < " << c.str() << " = " << (a < c ? "True" : "False") << std::endl;
  std::cout << a.str() << " > " << c.str() << " = " << (a > c ? "True" : "False") << std::endl;
  std::cout << a.str() << " <= " << c.str() << " = " << (a <= c ? "True" : "False") << std::endl;
  std::cout << a.str() << " >= " << c.str() << " = " << (a >= c ? "True" : "False") << std::endl;
  std::cout << a.str() << " == " << c.str() << " = " << (a == c ? "True" : "False") << std::endl;
  std::cout << a.str() << " != " << c.str() << " = " << (a != c ? "True" : "False") << std::endl;
  std::cout << a.str() << " < " << 10 << " = " << (a < 10 ? "True" : "False") << std::endl;
  std::cout << ((LongDouble)150.5).str() << " > " << ((LongDouble)10.).str() << " = " << (((LongDouble)150.5) > ((LongDouble)10.) ? "True" : "False") << std::endl;
  std::cout << a.str() << " < " << ((LongDouble)10.).str() << " = " << ((a < ((LongDouble)10.)) ? "True" : "False") << std::endl;
  std::cout << "====== Other ======" << std::endl;
  std::cout << "gcd(" << ((LongInt)123).str() << "," << ((LongInt)15).str() << ") = " << LongDouble::gcd((LongInt)123, (LongInt)15).str() << std::endl;
  return 0;
}
